version: "3"
services:
  mountebank:
    container_name: mountebank
    image: bbyars/mountebank:latest
    volumes:
    - ./imposters:/imposters
    ports:
    - 2525:2525
    - 18081:18081
    - 19081:19081
    command: mb --configfile /imposters/imposters.ejs --allowInjection